services:
  - type: web
    name: codinghtml-presentation
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: CREDENTIAL_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: SESSION_STORE
        value: sqlite
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 